<?php


/**
 * This class defines the structure of the 'sf_asset' table.
 *
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Thu Oct 14 14:01:16 2010
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.sfAssetsLibraryPlugin.lib.model.map
 */
class sfAssetTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.sfAssetsLibraryPlugin.lib.model.map.sfAssetTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('sf_asset');
		$this->setPhpName('sfAsset');
		$this->setClassname('sfAsset');
		$this->setPackage('plugins.sfAssetsLibraryPlugin.lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addForeignKey('FOLDER_ID', 'FolderId', 'INTEGER', 'sf_asset_folder', 'ID', true, null, null);
		$this->addColumn('FILENAME', 'Filename', 'VARCHAR', false, 255, null);
		$this->addColumn('DESCRIPTION_ANTIC', 'DescriptionAntic', 'LONGVARCHAR', false, null, null);
		$this->addColumn('AUTHOR', 'Author', 'VARCHAR', false, 255, null);
		$this->addColumn('COPYRIGHT', 'Copyright', 'VARCHAR', false, 100, null);
		$this->addColumn('TYPE', 'Type', 'VARCHAR', false, 10, null);
		$this->addColumn('FILESIZE', 'Filesize', 'INTEGER', false, null, null);
		$this->addColumn('RANK', 'Rank', 'INTEGER', false, null, null);
		$this->addColumn('IS_PUBLIC', 'IsPublic', 'BOOLEAN', false, null, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('sfAssetFolder', 'sfAssetFolder', RelationMap::MANY_TO_ONE, array('folder_id' => 'id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('SfAssetI18n', 'SfAssetI18n', RelationMap::ONE_TO_MANY, array('id' => 'id', ), 'CASCADE', null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', ),
			'symfony_i18n' => array('i18n_table' => 'sf_asset_i18n', ),
		);
	} // getBehaviors()

} // sfAssetTableMap
